spring.application.name=ai-interview-assistant
spring.datasource.url=jdbc:mysql://localhost:3306/ai_interview_db
spring.datasource.username=root
spring.datasource.password=rishi@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
